package com.ninja.dietician.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;

@Data
@DynamoDBTable(tableName = "DietProject_Table")
public class Morbidity {


	@JsonIgnore
	@DynamoDBHashKey(attributeName = "PK")
	@DynamoDBAutoGeneratedKey()
	private String pk;

	@JsonIgnore
	@DynamoDBAttribute(attributeName = "InfoType")
	private String infoType;

	@DynamoDBAttribute(attributeName = "MorbidityName")
	private String morbidityName;

	@DynamoDBAttribute(attributeName = "MorbidityTestId")
	private String morbidityTestId;

	@DynamoDBAttribute(attributeName = "MorbidityTestName")
	private String morbidityTestName;

	@DynamoDBAttribute(attributeName = "MorbidityTestUnit")
	private String morbidityTestUnit;

	@DynamoDBAttribute(attributeName = "MorbidityMarkerRef")
	private String morbidityTestMarkerRef;

	@JsonIgnore
	@DynamoDBAttribute(attributeName = "Createdon")
	private String createdOn;

	@JsonIgnore
	@DynamoDBAttribute(attributeName = "Modifiedon")
	private String modifiedOn;

}
